
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Copyright 2016 james.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * @author james
 */
public class main extends javax.swing.JFrame {
    dbConnection connection = new dbConnection();
    ArrayList<String> credentials = new ArrayList();
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxtbx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTxtbx = new javax.swing.JPasswordField();
        addressTxtbx = new javax.swing.JTextField();
        connectBttn = new javax.swing.JButton();
        connectLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        databaseLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userTxtbx = new javax.swing.JTextField();
        fNameTxtbx = new javax.swing.JTextField();
        lNameTxtbx = new javax.swing.JTextField();
        dept1Combo = new javax.swing.JComboBox<>();
        dept2Combo = new javax.swing.JComboBox<>();
        dept3Combo = new javax.swing.JComboBox<>();
        passTxtbx = new javax.swing.JPasswordField();
        userBttn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        closeBttn = new javax.swing.JButton();
        userLbl = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        defaultSupTxtFld = new javax.swing.JTextField();
        dataBttn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        serverAddressTxt = new javax.swing.JTextField();
        serverUserText = new javax.swing.JTextField();
        serverPasswordText = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        networkTxtbx = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        databaseUsernameTxtbx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        databasePasswordTxtbx = new javax.swing.JPasswordField();
        databaseBttn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Address:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User:");

        usernameTxtbx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameTxtbxKeyPressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password:");

        passwordTxtbx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtbxKeyPressed(evt);
            }
        });

        addressTxtbx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTxtbxKeyPressed(evt);
            }
        });

        connectBttn.setText("Connect");
        connectBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBttnActionPerformed(evt);
            }
        });

        connectLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        databaseLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setText("Username:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setText("First Name");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setText("Last Name:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setText("Department 1:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("Department 2:");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Department 3:");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel14.setText("Password:");

        userTxtbx.setEditable(false);
        userTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        userTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTxtbxKeyPressed(evt);
            }
        });

        fNameTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        fNameTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNameTxtbxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtbxKeyReleased(evt);
            }
        });

        lNameTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lNameTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lNameTxtbxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtbxKeyReleased(evt);
            }
        });

        dept1Combo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dept1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LTS", "Lifeguard", "ISC" }));
        dept1Combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dept1ComboKeyPressed(evt);
            }
        });

        dept2Combo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dept2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "LTS", "Lifeguard", "ISC" }));
        dept2Combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dept2ComboKeyPressed(evt);
            }
        });

        dept3Combo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dept3Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "LTS", "Lifeguard", "ISC" }));
        dept3Combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dept3ComboKeyPressed(evt);
            }
        });

        passTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        passTxtbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtbxActionPerformed(evt);
            }
        });
        passTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTxtbxKeyPressed(evt);
            }
        });

        userBttn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        userBttn.setText("Create First User");
        userBttn.setEnabled(false);
        userBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBttnActionPerformed(evt);
            }
        });

        closeBttn.setText("Close");
        closeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBttnActionPerformed(evt);
            }
        });

        userLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        userLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("Default SUP:");

        defaultSupTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        defaultSupTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultSupTxtFldActionPerformed(evt);
            }
        });
        defaultSupTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                defaultSupTxtFldKeyPressed(evt);
            }
        });

        dataBttn.setText("Create data file");
        dataBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBttnActionPerformed(evt);
            }
        });

        jLabel16.setText("Server Address:");

        jLabel17.setText("Username:");

        jLabel18.setText("Password:");

        serverAddressTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serverAddressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serverAddressTxtKeyPressed(evt);
            }
        });

        serverUserText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serverUserText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serverUserTextKeyPressed(evt);
            }
        });

        serverPasswordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serverPasswordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serverPasswordTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(defaultSupTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel18))))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serverUserText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(serverAddressTxt)
                                    .addComponent(serverPasswordText))))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(serverAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(serverPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultSupTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataBttn)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Data File", jPanel2);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("Network:");

        networkTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        networkTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                networkTxtbxKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel15.setText("Example: 192.168.1.% for network");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Database Username:");

        databaseUsernameTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        databaseUsernameTxtbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseUsernameTxtbxActionPerformed(evt);
            }
        });
        databaseUsernameTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                databaseUsernameTxtbxKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("Database User Password:");

        databasePasswordTxtbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        databasePasswordTxtbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                databasePasswordTxtbxKeyPressed(evt);
            }
        });

        databaseBttn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        databaseBttn.setText("Setup Database");
        databaseBttn.setEnabled(false);
        databaseBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseBttnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel19.setText("127.0.0.1 for local machine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(databaseBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(databaseUsernameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(networkTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(databasePasswordTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(databaseUsernameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databasePasswordTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databaseBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.getAccessibleContext().setAccessibleName("Example: 192.168.1.% for network");

        jTabbedPane1.addTab("Database", jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(connectBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(addressTxtbx))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameTxtbx)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passwordTxtbx)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(databaseLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(closeBttn)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel14))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dept3Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dept2Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dept1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(passTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addGap(61, 61, 61)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(fNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(userTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(addressTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(databaseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dept2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept3Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userBttn)
                .addGap(1, 1, 1)
                .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(closeBttn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBttnActionPerformed
        String password = new String (passwordTxtbx.getPassword());
        boolean status = connection.firstConnect(usernameTxtbx.getText(), password, addressTxtbx.getText());
        
        if (status)
        {
            connectBttn.setEnabled(false);
            databaseBttn.setEnabled(true);
            connectLbl.setText("Connected To Server");
            networkTxtbx.requestFocus();
        }
        else
        {
            connectLbl.setText("Unable To Connect To Server");
        }
    }//GEN-LAST:event_connectBttnActionPerformed

    private void databaseBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseBttnActionPerformed
        String dataPassword = new String(databasePasswordTxtbx.getPassword());
        String password = new String(passwordTxtbx.getPassword());
        System.out.println("Create Database");
        boolean result = connection.createDatabase();
        if (result) 
        {
            connection.close();
            result = connection.secondConnect(usernameTxtbx.getText(), password, addressTxtbx.getText());

            if (result) 
            {
                System.out.println("Create User Table");
                result = connection.createUserTable();

                if (result) 
                {
                    System.out.println("Create Lifeguard Table");
                    result = connection.createLifeguardTable();

                    if (result) 
                    {
                        System.out.println("Create LTS Shift Table");
                        result = connection.createLTSTable();

                        if (result) 
                        {
                            System.out.println("Create LTS Cover Table");
                            result = connection.createCoversTable();

                            if (result) 
                            {
                                System.out.println("Create ISC Table");
                                result = connection.createIscTable();

                                if (result) 
                                {
                                    System.out.println("Create Availabilty Table");
                                    result = connection.createAvailabilityTable();

                                    if (result) 
                                    {
                                        System.out.println("Add Keys And Constraints To Availability Table");
                                        result = connection.alterAvailabilityTable();

                                        if (result) 
                                        {
                                            System.out.println("Add Keys And Constraints To Lifeguard Table");
                                            result = connection.alterLifeguardTable();

                                            if (result) 
                                            {
                                                System.out.println("Add Keys And Constraints To LTS Covers Table");
                                                result = connection.alterCoversTable();

                                                if (result) 
                                                {
                                                    System.out.println("Add Keys And Constraints To LTS Shift Table");
                                                    result = connection.alterLtsTable();

                                                    if (result) 
                                                    {
                                                        System.out.println("Add Keys And Constraints To ISC Table");
                                                        result = connection.alterIscTable();

                                                        if (result) 
                                                        {
                                                            System.out.println("Create Location Table");      
                                                            result = connection.createLocationTable();

                                                            if (result) 
                                                            {
                                                                System.out.println("Insert First Location Entry");
                                                                result = connection.insertLocationEntry();

                                                                if (result) 
                                                                {
                                                                    System.out.println("Create Database User");
                                                                    result = connection.databaseUser(databaseUsernameTxtbx.getText(), networkTxtbx.getText(), dataPassword);

                                                                    if (result) 
                                                                    {
                                                                        System.out.println("Grant Database User Privilages");
                                                                        result = connection.databaseGrants(networkTxtbx.getText(), databaseUsernameTxtbx.getText());

                                                                        if (result) 
                                                                        {
                                                                            databaseLbl.setText("Database Configured");

                                                                            databaseBttn.setEnabled(false);
                                                                            userBttn.setEnabled(true);
                                                                            fNameTxtbx.requestFocus();
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_databaseBttnActionPerformed

    private void userBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBttnActionPerformed
        String pass = new String (passTxtbx.getPassword());
        boolean supervisor = true;
        boolean result = false;
        result = connection.addUser(userTxtbx.getText(), fNameTxtbx.getText(), lNameTxtbx.getText(), (String)dept1Combo.getSelectedItem(), (String)dept2Combo.getSelectedItem(), (String)dept3Combo.getSelectedItem(), supervisor, pass);
        
        if (result)
        {
            userBttn.setEnabled(false);
            userLbl.setText("First User Created");
        }
    }//GEN-LAST:event_userBttnActionPerformed

    private void closeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBttnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBttnActionPerformed

    private void addressTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            usernameTxtbx.requestFocusInWindow();
        }
    }//GEN-LAST:event_addressTxtbxKeyPressed

    private void usernameTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            passwordTxtbx.requestFocusInWindow();
        }
    }//GEN-LAST:event_usernameTxtbxKeyPressed

    private void passwordTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            connectBttn.doClick();
        }
    }//GEN-LAST:event_passwordTxtbxKeyPressed

    private void networkTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_networkTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            databaseUsernameTxtbx.requestFocus();
        }
    }//GEN-LAST:event_networkTxtbxKeyPressed

    private void databasePasswordTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_databasePasswordTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            databaseBttn.doClick();
        }
    }//GEN-LAST:event_databasePasswordTxtbxKeyPressed

    private void userTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            fNameTxtbx.requestFocus();
        }
    }//GEN-LAST:event_userTxtbxKeyPressed

    private void fNameTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            lNameTxtbx.requestFocus();
        }
    }//GEN-LAST:event_fNameTxtbxKeyPressed

    private void passTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            userBttn.doClick();
        }
    }//GEN-LAST:event_passTxtbxKeyPressed

    private void lNameTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtbxKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            dept1Combo.requestFocus();
        }
    }//GEN-LAST:event_lNameTxtbxKeyPressed

    private void dept1ComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dept1ComboKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            dept2Combo.requestFocus();
        }
    }//GEN-LAST:event_dept1ComboKeyPressed

    private void dept2ComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dept2ComboKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            dept3Combo.requestFocus();
        }
    }//GEN-LAST:event_dept2ComboKeyPressed

    private void dept3ComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dept3ComboKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            passTxtbx.requestFocus();
        }
    }//GEN-LAST:event_dept3ComboKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Database setup companion for \n"
                + "the aquatic roster software\n"
                + "Version 0.6");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void dataBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBttnActionPerformed
        credentials.add(serverUserText.getText());
        credentials.add(new String (serverPasswordText.getPassword()));
        credentials.add(serverAddressTxt.getText());
        credentials.add(defaultSupTxtFld.getText());
        save();
    }//GEN-LAST:event_dataBttnActionPerformed

    private void passTxtbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtbxActionPerformed

    private void fNameTxtbxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtbxKeyReleased
        userTxtbx.setText(fNameTxtbx.getText().concat("." + lNameTxtbx.getText()));
    }//GEN-LAST:event_fNameTxtbxKeyReleased

    private void lNameTxtbxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtbxKeyReleased
        userTxtbx.setText(fNameTxtbx.getText().concat("." + lNameTxtbx.getText()));
    }//GEN-LAST:event_lNameTxtbxKeyReleased

    private void defaultSupTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultSupTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultSupTxtFldActionPerformed

    private void databaseUsernameTxtbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_databaseUsernameTxtbxKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            databasePasswordTxtbx.requestFocus();
        }
    }//GEN-LAST:event_databaseUsernameTxtbxKeyPressed

    private void serverAddressTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverAddressTxtKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            serverUserText.requestFocus();
        }
    }//GEN-LAST:event_serverAddressTxtKeyPressed

    private void serverUserTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverUserTextKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            serverPasswordText.requestFocus();
        }
    }//GEN-LAST:event_serverUserTextKeyPressed

    private void serverPasswordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverPasswordTextKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            defaultSupTxtFld.requestFocus();
        }
    }//GEN-LAST:event_serverPasswordTextKeyPressed

    private void defaultSupTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_defaultSupTxtFldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            dataBttn.doClick();
        }
    }//GEN-LAST:event_defaultSupTxtFldKeyPressed

    private void databaseUsernameTxtbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseUsernameTxtbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_databaseUsernameTxtbxActionPerformed

    private String setPath()
    {
        File defaultPath = new File(System.getProperty("user.home"));
        System.out.println("default path: " + defaultPath);
        JFileChooser folderSelection = new JFileChooser();
        
        folderSelection.setCurrentDirectory(defaultPath);
        folderSelection.setDialogTitle("Save Location");
        folderSelection.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderSelection.setAcceptAllFileFilterUsed(false);
        String path = null;
        
        String seperator = System.getProperty("file.separator");

        if (folderSelection.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            path = folderSelection.getSelectedFile().getPath();
        }
        else
        {
            System.out.println("No Selection ");
        }
        path = path.concat(seperator);
        return path;
    }
    
    private void save()
    {
        try
        {
            String path = setPath();
            ObjectOutputStream outfile = new ObjectOutputStream(new FileOutputStream(path.concat("info.dat")));
            outfile.writeObject(credentials);
            outfile.close();
            JOptionPane.showMessageDialog(this,"Info File Written");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error writing file - " + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxtbx;
    private javax.swing.JButton closeBttn;
    private javax.swing.JButton connectBttn;
    private javax.swing.JLabel connectLbl;
    private javax.swing.JButton dataBttn;
    private javax.swing.JButton databaseBttn;
    private javax.swing.JLabel databaseLbl;
    private javax.swing.JPasswordField databasePasswordTxtbx;
    private javax.swing.JTextField databaseUsernameTxtbx;
    private javax.swing.JTextField defaultSupTxtFld;
    private javax.swing.JComboBox<String> dept1Combo;
    private javax.swing.JComboBox<String> dept2Combo;
    private javax.swing.JComboBox<String> dept3Combo;
    private javax.swing.JTextField fNameTxtbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lNameTxtbx;
    private javax.swing.JTextField networkTxtbx;
    private javax.swing.JPasswordField passTxtbx;
    private javax.swing.JPasswordField passwordTxtbx;
    private javax.swing.JTextField serverAddressTxt;
    private javax.swing.JPasswordField serverPasswordText;
    private javax.swing.JTextField serverUserText;
    private javax.swing.JButton userBttn;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userTxtbx;
    private javax.swing.JTextField usernameTxtbx;
    // End of variables declaration//GEN-END:variables
}
